### ISSUE TITLE
Bug: https://service.bundlewatch.io/store code=Request failed with status code 500

### ISSUE THREAD

**Issue by demns** [bundlewatch/bundlewatch#142] opened 2020-05-14 16:42 UTC
**What is the current behavior?**

[INFO] Retrieving comparison
[ERROR] Unable to fetch fileDetails for baseBranch=master from https://service.bundlewatch.io/store code=Request failed with status code 500

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm using both github action and just pure package.json entry, such as 
        `"bundlewatch": "cross-env CI_REPO_OWNER=*** CI_COMMIT_SHA=*** CI_REPO_NAME=*** CI_BRANCH=master BUNDLEWATCH_GITHUB_TOKEN=*** bundlewatch",`

**What is the expected behavior?**

Not 500 :)

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

Windows/docker ubuntu
bundlewatch version "0.2.6"

But! I'm able to see results breakdown, including going to correct url :)

**Comment by iamogbz** [comment] 2020-05-14 17:40
Caused by a dependency update in the bundlewatch-service repo. Should have been resolved by https://github.com/bundlewatch/service/pull/168

**Closed as completed by iamogbz** 2020-05-14 17:40 UTC

**Comment by demns** [comment] 2020-05-14 19:30
Thanks! Works now. Good job, that was fast!
